{{- $apiHostname := mowsJoinDomain .services.api.subdomain (ternary "localhost" .domain (eq .routing "local")) -}}
{{- $webHostname := mowsJoinDomain .services.web.subdomain (ternary "localhost" .domain (eq .routing "local")) -}}
{{- $martinHostname := mowsJoinDomain .services.martin.subdomain (ternary "localhost" .domain (eq .routing "local")) -}}
{{- if and .services.postgres.storage.volumeName .services.postgres.storage.absolutePath -}}
{{- fail "Cannot specify both volumeName and absolutePath for postgres storage" -}}
{{- end -}}

services:
    postgres:
        image: "{{ .services.postgres.image }}"
        container_name: omniviv-postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: {{ .services.postgres.database }}
        volumes:
            {{- if .services.postgres.storage.volumeName }}
            - {{ .services.postgres.storage.volumeName }}:/var/lib/postgresql/data
            {{- else if .services.postgres.storage.absolutePath }}
            - {{ .services.postgres.storage.absolutePath }}:/var/lib/postgresql/data
            {{- end }}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d {{ .services.postgres.database }}"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        networks:
            - internal
        shm_size: {{ .services.postgres.shmSize }}

    api:
        {{- if eq .services.api.build.enabled true }}
        build:
            context: "{{ .services.api.build.context }}"
            dockerfile: "{{ .services.api.build.dockerfile }}"
        {{- else }}
        image: "{{ .services.api.image }}"
        {{- end }}
        container_name: omniviv-api
        restart: unless-stopped
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            DATABASE_URL: "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/{{ .services.postgres.database }}"
        volumes:
            - ./config/api/config.yaml:/app/config.yaml:ro
            {{- if .services.api.data.storage.volumeName }}
            - {{ .services.api.data.storage.volumeName }}:/app/data
            {{- else if .services.api.data.storage.absolutePath }}
            - {{ .services.api.data.storage.absolutePath }}:/app/data
            {{- end }}
        mem_limit: 1g
        healthcheck:
            test: ["CMD", "/wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000/api/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s
        cpus: 2
        networks:
            - {{ .reverseProxy.network }}
            - internal
        labels:
            traefik:
                docker:
                    network: {{ .chart.projectName }}_{{ .reverseProxy.network }}
                enable: true
                http:
                    routers:
                        omniviv-api:
                            rule: "Host(`{{ $apiHostname }}`)"
                            entrypoints: {{ ternary "websecure" "web" .tls }}
                            service: omniviv-api
                        {{- if .lanIp }}
                        omniviv-api-lan:
                            rule: "Host(`{{ .lanIp }}`)"
                            entrypoints: web
                            service: omniviv-api
                        {{- end }}
                            {{- if eq .tls true }}
                            tls:
                                certresolver: "default"
                                domains:
                                    - main: "{{ .domain }}"
                                      sans: "*.{{ .domain }}"
                            {{- end }}
                    services:
                        omniviv-api:
                            loadbalancer:
                                server:
                                    port: "3000"

    web:
        {{- if eq .services.web.build.enabled true }}
        build:
            context: "{{ .services.web.build.context }}"
            dockerfile: "{{ .services.web.build.dockerfile }}"
        {{- else }}
        image: "{{ .services.web.image }}"
        {{- end }}
        container_name: omniviv-web
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "/wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:80/"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 5s
        environment:
            CSP_CONNECT_SRC: {{ ternary "https://" "http://" .tls }}{{ $apiHostname }} {{ ternary "wss://" "ws://" .tls }}{{ $apiHostname }} {{ ternary "https://" "http://" .tls }}{{ $martinHostname }}
        volumes:
            - ./config/frontend/config.json:/public/config.json:ro
        networks:
            - {{ .reverseProxy.network }}
        labels:
            traefik:
                docker:
                    network: {{ .chart.projectName }}_{{ .reverseProxy.network }}
                enable: true
                http:
                    routers:
                        omniviv-web:
                            rule: "Host(`{{ $webHostname }}`)"
                            entrypoints: {{ ternary "websecure" "web" .tls }}
                            service: omniviv-web
                            {{- if eq .tls true }}
                            tls:
                                certresolver: "default"
                                domains:
                                    - main: "{{ .domain }}"
                                      sans: "*.{{ .domain }}"
                            {{- end }}
                    services:
                        omniviv-web:
                            loadbalancer:
                                server:
                                    port: "80"

    martin:
        image: "{{ .services.martin.image }}"
        container_name: omniviv-martin
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 5s
        volumes:
            - "{{ .services.martin.dataPath }}mbtiles:/mbtiles:ro"
            - "{{ .services.martin.dataPath }}fonts:/fonts:ro"
            - "{{ .services.martin.dataPath }}sprites:/sprites:ro"
        command: /mbtiles --font /fonts
        networks:
            - {{ .reverseProxy.network }}
        labels:
            traefik:
                docker:
                    network: {{ .chart.projectName }}_{{ .reverseProxy.network }}
                enable: true
                http:
                    routers:
                        omniviv-martin:
                            rule: "Host(`{{ $martinHostname }}`)"
                            entrypoints: {{ ternary "websecure" "web" .tls }}
                            service: omniviv-martin
                            middlewares: omniviv-martin-cache
                            {{- if eq .tls true }}
                            tls:
                                certresolver: "default"
                                domains:
                                    - main: "{{ .domain }}"
                                      sans: "*.{{ .domain }}"
                            {{- end }}
                    middlewares:
                        omniviv-martin-cache:
                            headers:
                                customResponseHeaders:
                                    Cache-Control: "public, max-age={{ .services.martin.cacheSeconds }}"
                    services:
                        omniviv-martin:
                            loadbalancer:
                                server:
                                    port: "3000"

    {{- if eq .reverseProxy.create true }}
    traefik:
        image: traefik:v3
        container_name: omniviv-traefik
        restart: unless-stopped
        command:
            - "--providers.docker=true"
            - "--entrypoints.web.address=:80"
        networks:
            - {{ .reverseProxy.network }}
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
    {{- end }}

volumes:
    {{- if .services.postgres.storage.volumeName }}
    {{ .services.postgres.storage.volumeName }}:
    {{- end }}
    {{- if .services.api.data.storage.volumeName }}
    {{ .services.api.data.storage.volumeName }}:
    {{- end }}

networks:
    {{ .reverseProxy.network }}:
        {{- if ne .reverseProxy.create true }}
        external: true
        {{- end }}
    internal:
