#!/usr/bin/env bash
# Bundles all Maki SVG icons into a single TypeScript module.
# Run: bash scripts/bundle-icons.sh
set -euo pipefail

MAKI_DIR="$(dirname "$0")/../public/icons/maki"
OUT="$(dirname "$0")/../src/generated/maki-icons.ts"

echo "// Auto-generated by scripts/bundle-icons.sh — do not edit" > "$OUT"
echo "export const makiIcons: Record<string, string> = {" >> "$OUT"

for svg in "$MAKI_DIR"/*.svg; do
    name=$(basename "$svg" .svg)
    # Read SVG content, escape backticks and backslashes for template literal
    content=$(cat "$svg" | sed 's/\\/\\\\/g; s/`/\\`/g')
    echo "  \"$name\": \`$content\`," >> "$OUT"
done

echo "};" >> "$OUT"
echo "Generated $(ls "$MAKI_DIR"/*.svg | wc -l) icons → $OUT"
