routing: domain
tls: true

reverseProxy:
    create: false # Traefik already running on production server
    network: rp

domain: vindelicum.eu
lanIp: null

services:
    postgres:
        image: postgres:18-alpine
        database: omniviv
        storage:
            volumeName: omniviv-postgres-data
            absolutePath: null
        shmSize: 256mb
    api:
        subdomain: omniviv-api
        corsPermissive: false
        corsOrigins:
            - "https://omniviv.vindelicum.eu"
        data:
            storage:
                volumeName: omniviv-api-data
                absolutePath: null
        build:
            enabled: false
        image: ghcr.io/firstdorsal/omniviv-api:latest
    web:
        subdomain: omniviv
        build:
            enabled: false
        image: ghcr.io/firstdorsal/omniviv-frontend:latest
    martin:
        subdomain: omniviv-martin
        image: ghcr.io/maplibre/martin
        dataPath: ./data/
        cacheSeconds: 86400
    motis:
        subdomain: omniviv-motis
        image: ghcr.io/motis-project/motis:latest
        inputPath: ./data/motis/input/
        storage:
            volumeName: omniviv-motis-data
            absolutePath: null
        memLimit: 12g
