# Omniviv API Configuration

# CORS configuration
cors_permissive: {{ .services.api.corsPermissive | default false }}
{{- if .services.api.corsOrigins }}
cors_origins:
{{- range .services.api.corsOrigins }}
    - "{{ . }}"
{{- end }}
{{- end }}
