listen_addresses: '0.0.0.0:3000'

postgres:
  connection_string: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
  auto_publish: false

mbtiles:
  paths:
    - /mbtiles
    - /tiles/transit

fonts: /fonts
sprites: /sprites
