output_dir: /tiles
work_dir: /data
check_interval: "5m"

regions: []

world:
  enabled: false
  max_zoom: 7
  regen_interval: "7d"

transit:
  layers:
    - name: transit_stations
      function: transit_stations
      regen_interval: "1d"
      bbox: [10.85, 48.33, 10.93, 48.39]
      min_zoom: 0
      max_zoom: 15
      
    - name: transit_routes
      function: transit_routes
      regen_interval: "1d"
      bbox: [10.85, 48.33, 10.93, 48.39]
      min_zoom: 0
      max_zoom: 15
