use axum::extract::Query;
use axum::http::StatusCode;
use axum::{extract::State, routing::get, Json, Router};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::{FromRow, PgPool};
use utoipa::{IntoParams, ToSchema};

use crate::api::{ErrorResponse, internal_error};

/// Live status of one transit tile layer being generated by tilegen.
#[derive(Debug, Serialize, ToSchema, FromRow)]
pub struct TilegenLayerStatus {
    /// Layer name (matches the MBTiles filename and Martin source name)
    pub layer_name: String,
    /// Latest known phase: idle | running | committing | completed | failed
    pub phase: String,
    /// Last legacy status — kept for compatibility, derived from phase
    pub status: String,
    /// Tiles already written to the in-progress mbtiles
    pub tiles_done: i64,
    /// Estimated total tiles for the configured bbox + zoom range
    pub tiles_total: i64,
    /// Highest zoom level seen in the in-progress mbtiles, or null
    pub current_zoom: Option<i32>,
    /// Configured min zoom for this layer
    pub min_zoom: Option<i32>,
    /// Configured max zoom for this layer
    pub max_zoom: Option<i32>,
    /// Bounding box: [west, south, east, north] in WGS84
    pub bbox: Option<[f64; 4]>,
    /// Human-readable area description (e.g. "bayern", "10.85,48.33,...")
    pub area_label: Option<String>,
    /// When the current generation cycle started (NULL if never started)
    pub started_at: Option<DateTime<Utc>>,
    /// When the layer last completed successfully (NULL if never completed)
    pub last_generated_at: Option<DateTime<Utc>>,
    /// Duration of the last successful generation in milliseconds
    pub generation_duration_ms: i64,
    /// Size of the last completed mbtiles file in bytes
    pub file_size_bytes: i64,
    /// Last error message if the previous run failed
    pub error_message: Option<String>,
}

#[derive(Debug, Serialize, ToSchema)]
pub struct TilegenStatusResponse {
    pub layers: Vec<TilegenLayerStatus>,
}

#[derive(Debug, FromRow)]
struct StatusRow {
    layer_name: String,
    phase: String,
    status: String,
    tiles_done: i64,
    tiles_total: i64,
    current_zoom: Option<i32>,
    min_zoom: Option<i32>,
    max_zoom: Option<i32>,
    bbox_west: Option<f64>,
    bbox_south: Option<f64>,
    bbox_east: Option<f64>,
    bbox_north: Option<f64>,
    area_label: Option<String>,
    started_at: Option<DateTime<Utc>>,
    last_generated_at: Option<DateTime<Utc>>,
    generation_duration_ms: i64,
    file_size_bytes: i64,
    error_message: Option<String>,
}

/// Get live tile generation status for the diagnostics panel.
#[utoipa::path(
    get,
    path = "/api/tilegen/status",
    responses(
        (status = 200, description = "Tile generation status for all layers", body = TilegenStatusResponse),
        (status = 500, description = "Internal server error", body = ErrorResponse)
    ),
    tag = "tilegen"
)]
pub async fn get_status(
    State(pool): State<PgPool>,
) -> Result<Json<TilegenStatusResponse>, (StatusCode, Json<ErrorResponse>)> {
    let rows: Vec<StatusRow> = sqlx::query_as(
        r#"
        SELECT
            layer_name,
            COALESCE(phase, 'idle') AS phase,
            status,
            COALESCE(tiles_done, 0) AS tiles_done,
            COALESCE(tiles_total, 0) AS tiles_total,
            current_zoom,
            min_zoom,
            max_zoom,
            bbox_west, bbox_south, bbox_east, bbox_north,
            area_label,
            started_at,
            last_generated_at,
            COALESCE(generation_duration_ms, 0) AS generation_duration_ms,
            COALESCE(file_size_bytes, 0) AS file_size_bytes,
            error_message
        FROM tile_generation_state
        ORDER BY layer_name
        "#,
    )
    .fetch_all(&pool)
    .await
    .map_err(internal_error)?;

    let layers = rows
        .into_iter()
        .map(|r| {
            let bbox = match (r.bbox_west, r.bbox_south, r.bbox_east, r.bbox_north) {
                (Some(w), Some(s), Some(e), Some(n)) => Some([w, s, e, n]),
                _ => None,
            };
            TilegenLayerStatus {
                layer_name: r.layer_name,
                phase: r.phase,
                status: r.status,
                tiles_done: r.tiles_done,
                tiles_total: r.tiles_total,
                current_zoom: r.current_zoom,
                min_zoom: r.min_zoom,
                max_zoom: r.max_zoom,
                bbox,
                area_label: r.area_label,
                started_at: r.started_at,
                last_generated_at: r.last_generated_at,
                generation_duration_ms: r.generation_duration_ms,
                file_size_bytes: r.file_size_bytes,
                error_message: r.error_message,
            }
        })
        .collect();

    Ok(Json(TilegenStatusResponse { layers }))
}

/// One past generation run.
#[derive(Debug, Serialize, ToSchema, FromRow)]
pub struct TilegenHistoryEntry {
    pub id: i64,
    pub layer_name: String,
    pub started_at: DateTime<Utc>,
    pub completed_at: DateTime<Utc>,
    pub duration_ms: i64,
    pub tiles_done: i64,
    pub tiles_total: i64,
    pub file_size_bytes: i64,
    pub area_label: Option<String>,
    pub status: String,
    pub error_message: Option<String>,
}

#[derive(Debug, Serialize, ToSchema)]
pub struct TilegenHistoryResponse {
    pub entries: Vec<TilegenHistoryEntry>,
}

#[derive(Debug, Deserialize, IntoParams)]
pub struct HistoryQuery {
    /// Filter to a single layer (optional). When omitted, returns rows for all layers.
    pub layer: Option<String>,
    /// Maximum number of entries to return. Default 20, max 200.
    pub limit: Option<i64>,
}

/// Get past tile generation runs (most recent first).
#[utoipa::path(
    get,
    path = "/api/tilegen/history",
    params(HistoryQuery),
    responses(
        (status = 200, description = "Past generation runs", body = TilegenHistoryResponse),
        (status = 500, description = "Internal server error", body = ErrorResponse)
    ),
    tag = "tilegen"
)]
pub async fn get_history(
    State(pool): State<PgPool>,
    Query(query): Query<HistoryQuery>,
) -> Result<Json<TilegenHistoryResponse>, (StatusCode, Json<ErrorResponse>)> {
    let limit = query.limit.unwrap_or(20).clamp(1, 200);
    let entries: Vec<TilegenHistoryEntry> = sqlx::query_as(
        r#"
        SELECT id, layer_name, started_at, completed_at, duration_ms,
               tiles_done, tiles_total, file_size_bytes,
               area_label, status, error_message
        FROM tile_generation_history
        WHERE ($1::text IS NULL OR layer_name = $1)
        ORDER BY completed_at DESC
        LIMIT $2
        "#,
    )
    .bind(query.layer.as_deref())
    .bind(limit)
    .fetch_all(&pool)
    .await
    .map_err(internal_error)?;

    Ok(Json(TilegenHistoryResponse { entries }))
}

#[derive(Debug, Deserialize, IntoParams)]
pub struct AreaPolygonQuery {
    /// Area name (e.g. "bayern", "germany", "nrw")
    pub name: String,
}

#[derive(Debug, Serialize, ToSchema)]
pub struct AreaPolygonResponse {
    /// GeoJSON Feature object with the polygon, or null if unknown
    pub feature: Option<serde_json::Value>,
}

/// Return the actual administrative polygon for a named area (German
/// Bundesland or Germany), assembled from the OSM admin relation in
/// the slim osm2pgsql tables. Used by the diagnostics panel to draw
/// the real state border on the map instead of a bounding rectangle.
#[utoipa::path(
    get,
    path = "/api/tilegen/area-polygon",
    params(AreaPolygonQuery),
    responses(
        (status = 200, description = "Area polygon as GeoJSON Feature", body = AreaPolygonResponse),
        (status = 500, description = "Internal server error", body = ErrorResponse)
    ),
    tag = "tilegen"
)]
pub async fn get_area_polygon(
    State(pool): State<PgPool>,
    Query(query): Query<AreaPolygonQuery>,
) -> Result<Json<AreaPolygonResponse>, (StatusCode, Json<ErrorResponse>)> {
    let row: (Option<serde_json::Value>,) =
        sqlx::query_as("SELECT osm_admin_polygon($1)")
            .bind(&query.name)
            .fetch_one(&pool)
            .await
            .map_err(internal_error)?;
    Ok(Json(AreaPolygonResponse { feature: row.0 }))
}

pub fn router(pool: PgPool) -> Router {
    Router::new()
        .route("/status", get(get_status))
        .route("/history", get(get_history))
        .route("/area-polygon", get(get_area_polygon))
        .with_state(pool)
}
