[env:esp32s3-display]
; Standard espressif32 doesn't support Arduino core v3.1.x; use pioarduino fork
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
platform_packages =
    platformio/framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git#3.1.1
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_build.partitions = partitions.csv
build_flags =
    -D BOARD_HAS_PSRAM
    -D LV_CONF_INCLUDE_SIMPLE
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -I.
lib_deps =
    https://github.com/lvgl/lvgl.git#v8.4.0
    lovyan03/LovyanGFX@^1.2
    bblanchon/ArduinoJson@^7.4
